apiVersion: batch/v1
kind: Job
metadata:
  name: create-imagestream-rag11-sep16-1-gitops
  namespace: redhat-ods-applications
spec:  
  template:         
    metadata:
      name: create-imagestream-rag11-sep16-1-gitops
    spec:  
      # serviceAccountName: imagestream-job
      containers:
      - name: create-imagestream
        image: quay.io/redhat-appstudio/appstudio-utils:5bd7d6cb0b17f9f2eab043a8ad16ba3d90551bc2@sha256:8c7fcf86af40c71aeb58e4279625c8308af5144e2f6b8e28b0ec7e795260e5f7

        command:
        - /bin/bash
        - -c
        - |
          # Create SA
          kind: ServiceAccount
          apiVersion: v1
          metadata:
            name: imagestream-job
            namespace: redhat-ods-applications

          # Create role
          kind: Role
          apiVersion: rbac.authorization.k8s.io/v1
          metadata:
            name: imagestream-job-role
            namespace: redhat-ods-applications
          rules:
            - verbs:
                - get
                - list
                - delete
                - create
                - watch
                - update
                - patch
              apiGroups:
                - ""
              resources:
                - serviceaccounts
            - verbs:
                - get
                - create
                - list
                - delete
                - update
                - watch
                - patch
              apiGroups:
                - "batch"
              resources:
                - jobs
            - verbs:
                - get
                - create
                - list
              apiGroups:
                - "image.openshift.io"
              resources:
                - imagestreams
          
          # Create Role Binding
          kind: RoleBinding
          apiVersion: rbac.authorization.k8s.io/v1
          metadata:
            name: imagestream-job-rolebinding
            namespace: redhat-ods-applications
          subjects:
            - kind: ServiceAccount
              name: imagestream-job
              namespace: redhat-ods-applications
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: Role
            name: imagestream-job-role

          # Check for image stream and create it not present
          echo "Checking if the image stream exist"
          if ! oc get is custom-sqlite3-odh-minimal-notebook-container -n redhat-ods-applications >/dev/null 2>&1 ; then
            echo "The image stream does not exist, a new image stream will be created"
            cat <<EOF | oc apply -f -
            kind: ImageStream
            apiVersion: image.openshift.io/v1
            metadata:
              annotations:
                opendatahub.io/notebook-image-name: custom-sqlite3-odh-minimal-notebook-container
                opendatahub.io/notebook-image-url: 'quay.io/redhat-ai-dev/odh-minimal-notebook-container:v2-2024a-20240523-sqlite3'
              name: custom-sqlite3-odh-minimal-notebook-container
              namespace: redhat-ods-applications
              labels:
                opendatahub.io/dashboard: 'true'
                opendatahub.io/notebook-image: 'true'
            spec:
              lookupPolicy:
                local: true
              tags:
                - name: v2-2024a-20240523-sqlite3
                  annotations:
                    openshift.io/imported-from: 'quay.io/redhat-ai-dev/odh-minimal-notebook-container:v2-2024a-20240523-sqlite3'
                  from:
                    kind: DockerImage
                    name: 'quay.io/redhat-ai-dev/odh-minimal-notebook-container:v2-2024a-20240523-sqlite3'
                  generation: 2
                  importPolicy:
                    importMode: Legacy
                  referencePolicy:
                    type: Source
          EOF
          else
            echo "Image stream is already present, skipping create"
          fi
      restartPolicy: Never
